/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISuOracle } from "./ISuOracle";
export type { ISuOracleAggregator } from "./ISuOracleAggregator";
export type { ISuUniV3Oracle } from "./ISuUniV3Oracle";
