/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SuAccessControlSingleton } from "./SuAccessControlSingleton";
export type { SuAccessRoles } from "./SuAccessRoles";
export type { SuAuthenticated } from "./SuAuthenticated";
