/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockOracle__factory } from "./MockOracle__factory";
export { MockWBTC__factory } from "./MockWBTC__factory";
