/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISuOracle,
  ISuOracleInterface,
} from "../../../../contracts/interfaces/oracle/ISuOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getFiatPrice1e18",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISuOracle__factory {
  static readonly abi = _abi;
  static createInterface(): ISuOracleInterface {
    return new utils.Interface(_abi) as ISuOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISuOracle {
    return new Contract(address, _abi, signerOrProvider) as ISuOracle;
  }
}
